name: Build CLI

on:
  push:
    branches:
      - main

jobs:
  buildCli:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
      - uses: graalvm/setup-graalvm@v1
        with:
          version: '22.1.0'
          java-version: '17'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Spotless
        uses: gradle/gradle-build-action@v2
        with:
          arguments: spotlessCheck
      - name: Test
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test
      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: :jbeancount-cli:nativeBuild
      - name: Upload Ubuntu CLI executable
        if: ${{ matrix.os == 'ubuntu-latest'}}
        uses: actions/upload-artifact@v3
        with:
          name: ubuntu-cli-executable
          path: jbeancount-cli/build/native/nativeBuild/jbeancount
      - name: Upload Windows CLI executable
        if: ${{ matrix.os == 'windows-latest'}}
        uses: actions/upload-artifact@v3
        with:
          name: windows-cli-executable
          path: jbeancount-cli/build/native/nativeBuild/jbeancount.exe
