name: Build & Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: macos
            arch: aarch64
            runner: macos-latest
    runs-on: ${{ matrix.runner }}
    name: Build for ${{ matrix.os }} ${{ matrix.arch }}
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Extract version
        id: version
        run: |
          echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
          echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '23'
          distribution: 'graalvm-community'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          check-for-updates: 'false'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build Native Image
        run: |
          ./gradlew cli:nativeCompile
          mkdir -p jbeancount-${{ matrix.os }}-${{ matrix.arch }}/bin
          mv cli/build/native/nativeCompile/cli jbeancount-${{ matrix.os }}-${{ matrix.arch }}/bin/jbeancount
          zip -r jbeancount-${{ matrix.os }}-${{ matrix.arch }}.zip jbeancount-${{ matrix.os }}-${{ matrix.arch }}
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: jbeancount-${{ matrix.os }}-${{ matrix.arch }}
          path: jbeancount-${{ matrix.os }}-${{ matrix.arch }}.zip
          if-no-files-found: error
  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Download all built artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist
          pattern: jbeancount-*
          merge-multiple: true
      - name: Release with JReleaser
        uses: jreleaser/release-action@v2
        env:
          JRELEASER_PROJECT_VERSION: ${{ needs.build.outputs.version }}
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GH_PAT }}

